FROM ruby:3.3.6-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential git libpq-dev libyaml-dev pkg-config curl && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

COPY bin/docker-entrypoint-dev /usr/bin/docker-entrypoint-dev
RUN chmod +x /usr/bin/docker-entrypoint-dev

EXPOSE 3000

ENTRYPOINT ["docker-entrypoint-dev"]
CMD ["rails", "server", "-b", "0.0.0.0"]
